### ISSUE TITLE
Improper grammar for single attribute for new type

### ISSUE THREAD

**Issue by DanielKwolek** [fabriciocolombo/sonar-delphi#14]
Analyzing project craches during parsing files with single attribute for new type. E.G. 

[DatabaseIndex([diUnique], ldRecord, ldHistoryTag)]
TNewTableType = class(TTableType<TRecordType>);

**Comment by fabriciocolombo** [comment]
Fixed by commit 317f9aa75d4d733522a41ad0bc96f3e880b20c5d

Thanks @DanielKwolek
