### ISSUE TITLE
Suggestion: Include sample project for default runner

### ISSUE THREAD

**Issue by darianmiller** [fabriciocolombo/sonar-delphi#35]
The sample projects for the old Delphi plugin are no longer included in latest versions of: https://github.com/SonarSource/sonar-examples/tree/master/projects/languages

Makes it a little harder to get started with SonarQube and the default runner.

**Comment by fabriciocolombo** [comment]
Thank you for the suggestion. It will be included soon.

**Comment by fabriciocolombo** [comment]
Closed this in 70dc6da644328b358b5d62a4a85a74c26d0cf699
