### ISSUE TITLE
No metric (PUBLIC_API) for org.sonar.plugins.delphi.metrics.ComplexityMetrics

### ISSUE THREAD

**Issue by tkapusta** [fabriciocolombo/sonar-delphi#36]
Greetings,
I have problem running Delphi project analysis. Every time after parsing I am getting error:
    No metric (PUBLIC_API) for org.sonar.plugins.delphi.metrics.ComplexityMetrics@46f3a146

To be honest I am not sure what metric in Sonar is, and where to start debugging. the articles covering metrics in Sonar Docs are unavailable :/

**Comment by fabriciocolombo** [comment]
What  SonarQube and Delphi Plugin version are you using?

**Comment by tkapusta** [comment]
SonarQube 4.5.2, plugin 0.3.3

**Comment by fabriciocolombo** [comment]
I can't reproduce the error using the same versions.
Please, run the analysis using debug mode (-X,--debug) and attach the log file.

**Comment by tkapusta** [comment]
Log attached
[Delphilog.txt](https://github.com/fabriciocolombo/sonar-delphi/files/86990/Delphilog.txt)

Edit - I found files which cause this error. One of them (the shortest, changed extension so github wil allow posting it):
[FailingScript.txt](https://github.com/fabriciocolombo/sonar-delphi/files/87188/FailingScript.txt)

**Comment by fabriciocolombo** [comment]
Please, try with this snapshot: [0.3.4-16012016.jar](https://github.com/fabriciocolombo/sonar-delphi/releases/download/0.3.4-SNAPSHOT/sonar-delphi-plugin-0.3.4-16012016.jar).
Feel free to reopen if something goes wrong.
